### ISSUE TITLE
spec_urls needed: require mdn_url

### ISSUE THREAD

**Issue by Elchi3** [ddbeck/bcd-utils#1]
I was looking some more at https://gist.github.com/ddbeck/5fc593ae6b486bb0d63468591b7dfc69 and @sideshowbarker and I actually finished the html section. So, I wondered why there are html entries in this list.

It contains entries like these:

html.elements.a.charset
html.elements.a.coords
html.elements.a.download
html.elements.a.href
html.elements.a.href.href_top
html.elements.a.hreflang
html.elements.a.implicit_noopener
html.elements.a.name
html.elements.a.ping

These features have no `mdn_url` and so they also need no `spec_url`, I would say. At least we're not planning to add spec_urls for these for the moment.

**Comment by sideshowbarker** [comment]
> These features have no `mdn_url` and so they also need no `spec_url`, I would say. At least we're not planning to add spec_urls for these for the moment.

To be clear on one thing: The reason the only `spec_url` values that got added to the tree so far were limited to features that also have `mdn_url` values is that because the tooling I wrote for identifying the spec URLs does it by scraping the Specifications tables in MDN, the tooling can necessarily only do that it it knows there’s an MDN article to scrape. So I guess we need to consider whether we want that tooling limitation to prevent us from adding spec URLs for cases where there’s no MDN article — if we’ve been able to identify the spec URLs by some other means (which I guess is the case here?).

**Comment by Elchi3** [comment]
Right, we can always add more later. However, to track a first milestone of this project, maybe we could have a list that gives us just the features with an mdn_url? 

Having completed just these, it will be useful as we will have reached two major goals:
- the data in the w3c fork is completely upstreamed
- we can source the "Specifications" section from BCD because all features with an MDN page have a spec_url

**Comment by ddbeck** [comment]
To illustrate things, I updated [`examples/spec_url_needed.js`](https://github.com/ddbeck/bcd-utils/blob/main/examples/spec_url_needed.js) to produce two lists for the milestones: the first with `standard_track` features that have `mdn_url` missing `spec_url` and the second with all `standard_track` features missing `spec_url`:

- https://gist.github.com/ddbeck/5fc593ae6b486bb0d63468591b7dfc69#milestone-1
- https://gist.github.com/ddbeck/5fc593ae6b486bb0d63468591b7dfc69#milestone-2

**Comment by Elchi3** [comment]
Thank you, Daniel! 👍
